// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sql/v1/sql.proto

package sqlv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/litesql/go-ha/api/sql/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "sql.v1.DatabaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceQueryProcedure is the fully-qualified name of the DatabaseService's Query RPC.
	DatabaseServiceQueryProcedure = "/sql.v1.DatabaseService/Query"
	// DatabaseServiceDataSourceNamesProcedure is the fully-qualified name of the DatabaseService's
	// DataSourceNames RPC.
	DatabaseServiceDataSourceNamesProcedure = "/sql.v1.DatabaseService/DataSourceNames"
	// DatabaseServiceDownloadProcedure is the fully-qualified name of the DatabaseService's Download
	// RPC.
	DatabaseServiceDownloadProcedure = "/sql.v1.DatabaseService/Download"
	// DatabaseServiceLatestSnapshotProcedure is the fully-qualified name of the DatabaseService's
	// LatestSnapshot RPC.
	DatabaseServiceLatestSnapshotProcedure = "/sql.v1.DatabaseService/LatestSnapshot"
	// DatabaseServiceReplicationIDsProcedure is the fully-qualified name of the DatabaseService's
	// ReplicationIDs RPC.
	DatabaseServiceReplicationIDsProcedure = "/sql.v1.DatabaseService/ReplicationIDs"
)

// DatabaseServiceClient is a client for the sql.v1.DatabaseService service.
type DatabaseServiceClient interface {
	Query(context.Context) *connect.BidiStreamForClient[v1.QueryRequest, v1.QueryResponse]
	DataSourceNames(context.Context, *connect.Request[v1.DataSourceNamesRequest]) (*connect.Response[v1.DataSourceNamesResponse], error)
	Download(context.Context, *connect.Request[v1.DownloadRequest]) (*connect.ServerStreamForClient[v1.DownloadResponse], error)
	LatestSnapshot(context.Context, *connect.Request[v1.LatestSnapshotRequest]) (*connect.ServerStreamForClient[v1.LatestSnapshotResponse], error)
	ReplicationIDs(context.Context, *connect.Request[v1.ReplicationIDsRequest]) (*connect.Response[v1.ReplicationIDsResponse], error)
}

// NewDatabaseServiceClient constructs a client for the sql.v1.DatabaseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := v1.File_sql_v1_sql_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		query: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		dataSourceNames: connect.NewClient[v1.DataSourceNamesRequest, v1.DataSourceNamesResponse](
			httpClient,
			baseURL+DatabaseServiceDataSourceNamesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DataSourceNames")),
			connect.WithClientOptions(opts...),
		),
		download: connect.NewClient[v1.DownloadRequest, v1.DownloadResponse](
			httpClient,
			baseURL+DatabaseServiceDownloadProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Download")),
			connect.WithClientOptions(opts...),
		),
		latestSnapshot: connect.NewClient[v1.LatestSnapshotRequest, v1.LatestSnapshotResponse](
			httpClient,
			baseURL+DatabaseServiceLatestSnapshotProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("LatestSnapshot")),
			connect.WithClientOptions(opts...),
		),
		replicationIDs: connect.NewClient[v1.ReplicationIDsRequest, v1.ReplicationIDsResponse](
			httpClient,
			baseURL+DatabaseServiceReplicationIDsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ReplicationIDs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	query           *connect.Client[v1.QueryRequest, v1.QueryResponse]
	dataSourceNames *connect.Client[v1.DataSourceNamesRequest, v1.DataSourceNamesResponse]
	download        *connect.Client[v1.DownloadRequest, v1.DownloadResponse]
	latestSnapshot  *connect.Client[v1.LatestSnapshotRequest, v1.LatestSnapshotResponse]
	replicationIDs  *connect.Client[v1.ReplicationIDsRequest, v1.ReplicationIDsResponse]
}

// Query calls sql.v1.DatabaseService.Query.
func (c *databaseServiceClient) Query(ctx context.Context) *connect.BidiStreamForClient[v1.QueryRequest, v1.QueryResponse] {
	return c.query.CallBidiStream(ctx)
}

// DataSourceNames calls sql.v1.DatabaseService.DataSourceNames.
func (c *databaseServiceClient) DataSourceNames(ctx context.Context, req *connect.Request[v1.DataSourceNamesRequest]) (*connect.Response[v1.DataSourceNamesResponse], error) {
	return c.dataSourceNames.CallUnary(ctx, req)
}

// Download calls sql.v1.DatabaseService.Download.
func (c *databaseServiceClient) Download(ctx context.Context, req *connect.Request[v1.DownloadRequest]) (*connect.ServerStreamForClient[v1.DownloadResponse], error) {
	return c.download.CallServerStream(ctx, req)
}

// LatestSnapshot calls sql.v1.DatabaseService.LatestSnapshot.
func (c *databaseServiceClient) LatestSnapshot(ctx context.Context, req *connect.Request[v1.LatestSnapshotRequest]) (*connect.ServerStreamForClient[v1.LatestSnapshotResponse], error) {
	return c.latestSnapshot.CallServerStream(ctx, req)
}

// ReplicationIDs calls sql.v1.DatabaseService.ReplicationIDs.
func (c *databaseServiceClient) ReplicationIDs(ctx context.Context, req *connect.Request[v1.ReplicationIDsRequest]) (*connect.Response[v1.ReplicationIDsResponse], error) {
	return c.replicationIDs.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the sql.v1.DatabaseService service.
type DatabaseServiceHandler interface {
	Query(context.Context, *connect.BidiStream[v1.QueryRequest, v1.QueryResponse]) error
	DataSourceNames(context.Context, *connect.Request[v1.DataSourceNamesRequest]) (*connect.Response[v1.DataSourceNamesResponse], error)
	Download(context.Context, *connect.Request[v1.DownloadRequest], *connect.ServerStream[v1.DownloadResponse]) error
	LatestSnapshot(context.Context, *connect.Request[v1.LatestSnapshotRequest], *connect.ServerStream[v1.LatestSnapshotResponse]) error
	ReplicationIDs(context.Context, *connect.Request[v1.ReplicationIDsRequest]) (*connect.Response[v1.ReplicationIDsResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := v1.File_sql_v1_sql_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceQueryHandler := connect.NewBidiStreamHandler(
		DatabaseServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(databaseServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDataSourceNamesHandler := connect.NewUnaryHandler(
		DatabaseServiceDataSourceNamesProcedure,
		svc.DataSourceNames,
		connect.WithSchema(databaseServiceMethods.ByName("DataSourceNames")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDownloadHandler := connect.NewServerStreamHandler(
		DatabaseServiceDownloadProcedure,
		svc.Download,
		connect.WithSchema(databaseServiceMethods.ByName("Download")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceLatestSnapshotHandler := connect.NewServerStreamHandler(
		DatabaseServiceLatestSnapshotProcedure,
		svc.LatestSnapshot,
		connect.WithSchema(databaseServiceMethods.ByName("LatestSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceReplicationIDsHandler := connect.NewUnaryHandler(
		DatabaseServiceReplicationIDsProcedure,
		svc.ReplicationIDs,
		connect.WithSchema(databaseServiceMethods.ByName("ReplicationIDs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sql.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceQueryProcedure:
			databaseServiceQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceDataSourceNamesProcedure:
			databaseServiceDataSourceNamesHandler.ServeHTTP(w, r)
		case DatabaseServiceDownloadProcedure:
			databaseServiceDownloadHandler.ServeHTTP(w, r)
		case DatabaseServiceLatestSnapshotProcedure:
			databaseServiceLatestSnapshotHandler.ServeHTTP(w, r)
		case DatabaseServiceReplicationIDsProcedure:
			databaseServiceReplicationIDsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) Query(context.Context, *connect.BidiStream[v1.QueryRequest, v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sql.v1.DatabaseService.Query is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DataSourceNames(context.Context, *connect.Request[v1.DataSourceNamesRequest]) (*connect.Response[v1.DataSourceNamesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sql.v1.DatabaseService.DataSourceNames is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Download(context.Context, *connect.Request[v1.DownloadRequest], *connect.ServerStream[v1.DownloadResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sql.v1.DatabaseService.Download is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) LatestSnapshot(context.Context, *connect.Request[v1.LatestSnapshotRequest], *connect.ServerStream[v1.LatestSnapshotResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sql.v1.DatabaseService.LatestSnapshot is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ReplicationIDs(context.Context, *connect.Request[v1.ReplicationIDsRequest]) (*connect.Response[v1.ReplicationIDsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sql.v1.DatabaseService.ReplicationIDs is not implemented"))
}
