// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sql/v1/sql.proto

package sqlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED QueryType = 0
	QueryType_QUERY_TYPE_EXEC_UPDATE QueryType = 1
	QueryType_QUERY_TYPE_EXEC_QUERY  QueryType = 2
	QueryType_QUERY_TYPE_PING        QueryType = 3
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_EXEC_UPDATE",
		2: "QUERY_TYPE_EXEC_QUERY",
		3: "QUERY_TYPE_PING",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED": 0,
		"QUERY_TYPE_EXEC_UPDATE": 1,
		"QUERY_TYPE_EXEC_QUERY":  2,
		"QUERY_TYPE_PING":        3,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_sql_v1_sql_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_sql_v1_sql_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{0}
}

type CangeSetRequestType int32

const (
	CangeSetRequestType_CHANGESET_REQUEST_TYPE_PING             CangeSetRequestType = 0
	CangeSetRequestType_CHANGESET_REQUEST_TYPE_PREPARE          CangeSetRequestType = 1
	CangeSetRequestType_CHANGESET_REQUEST_TYPE_COMMIT           CangeSetRequestType = 2
	CangeSetRequestType_CHANGESET_REQUEST_TYPE_ABORT            CangeSetRequestType = 3
	CangeSetRequestType_CHANGESET_REQUEST_TYPE_UNDO             CangeSetRequestType = 4
	CangeSetRequestType_CHANGESET_REQUEST_TYPE_UNDO_AFTER_CRASH CangeSetRequestType = 5
)

// Enum value maps for CangeSetRequestType.
var (
	CangeSetRequestType_name = map[int32]string{
		0: "CHANGESET_REQUEST_TYPE_PING",
		1: "CHANGESET_REQUEST_TYPE_PREPARE",
		2: "CHANGESET_REQUEST_TYPE_COMMIT",
		3: "CHANGESET_REQUEST_TYPE_ABORT",
		4: "CHANGESET_REQUEST_TYPE_UNDO",
		5: "CHANGESET_REQUEST_TYPE_UNDO_AFTER_CRASH",
	}
	CangeSetRequestType_value = map[string]int32{
		"CHANGESET_REQUEST_TYPE_PING":             0,
		"CHANGESET_REQUEST_TYPE_PREPARE":          1,
		"CHANGESET_REQUEST_TYPE_COMMIT":           2,
		"CHANGESET_REQUEST_TYPE_ABORT":            3,
		"CHANGESET_REQUEST_TYPE_UNDO":             4,
		"CHANGESET_REQUEST_TYPE_UNDO_AFTER_CRASH": 5,
	}
)

func (x CangeSetRequestType) Enum() *CangeSetRequestType {
	p := new(CangeSetRequestType)
	*p = x
	return p
}

func (x CangeSetRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CangeSetRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_sql_v1_sql_proto_enumTypes[1].Descriptor()
}

func (CangeSetRequestType) Type() protoreflect.EnumType {
	return &file_sql_v1_sql_proto_enumTypes[1]
}

func (x CangeSetRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CangeSetRequestType.Descriptor instead.
func (CangeSetRequestType) EnumDescriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{1}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          QueryType              `protobuf:"varint,1,opt,name=type,proto3,enum=sql.v1.QueryType" json:"type,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Params        []*NamedValue          `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	ReplicationId string                 `protobuf:"bytes,4,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetType() QueryType {
	if x != nil {
		return x.Type
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParams() []*NamedValue {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

type NamedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ordinal       int64                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedValue) Reset() {
	*x = NamedValue{}
	mi := &file_sql_v1_sql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedValue) ProtoMessage() {}

func (x *NamedValue) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedValue.ProtoReflect.Descriptor instead.
func (*NamedValue) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{1}
}

func (x *NamedValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedValue) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *NamedValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultSet     *Data                  `protobuf:"bytes,1,opt,name=result_set,json=resultSet,proto3" json:"result_set,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	LastInsertId  int64                  `protobuf:"varint,3,opt,name=last_insert_id,json=lastInsertId,proto3" json:"last_insert_id,omitempty"`
	Txseq         uint64                 `protobuf:"varint,4,opt,name=txseq,proto3" json:"txseq,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetResultSet() *Data {
	if x != nil {
		return x.ResultSet
	}
	return nil
}

func (x *QueryResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryResponse) GetLastInsertId() int64 {
	if x != nil {
		return x.LastInsertId
	}
	return 0
}

func (x *QueryResponse) GetTxseq() uint64 {
	if x != nil {
		return x.Txseq
	}
	return 0
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_sql_v1_sql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Data) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*anypb.Any           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_sql_v1_sql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetValues() []*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

type DataSourceNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceNamesRequest) Reset() {
	*x = DataSourceNamesRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceNamesRequest) ProtoMessage() {}

func (x *DataSourceNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceNamesRequest.ProtoReflect.Descriptor instead.
func (*DataSourceNamesRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{5}
}

type DataSourceNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           []string               `protobuf:"bytes,1,rep,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceNamesResponse) Reset() {
	*x = DataSourceNamesResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceNamesResponse) ProtoMessage() {}

func (x *DataSourceNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceNamesResponse.ProtoReflect.Descriptor instead.
func (*DataSourceNamesResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{6}
}

func (x *DataSourceNamesResponse) GetDsn() []string {
	if x != nil {
		return x.Dsn
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId string                 `protobuf:"bytes,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LatestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId string                 `protobuf:"bytes,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestSnapshotRequest) Reset() {
	*x = LatestSnapshotRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestSnapshotRequest) ProtoMessage() {}

func (x *LatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*LatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{9}
}

func (x *LatestSnapshotRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

type LatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestSnapshotResponse) Reset() {
	*x = LatestSnapshotResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestSnapshotResponse) ProtoMessage() {}

func (x *LatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*LatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{10}
}

func (x *LatestSnapshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplicationIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationIDsRequest) Reset() {
	*x = ReplicationIDsRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationIDsRequest) ProtoMessage() {}

func (x *ReplicationIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationIDsRequest.ProtoReflect.Descriptor instead.
func (*ReplicationIDsRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{11}
}

type ReplicationIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId []string               `protobuf:"bytes,1,rep,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationIDsResponse) Reset() {
	*x = ReplicationIDsResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationIDsResponse) ProtoMessage() {}

func (x *ReplicationIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationIDsResponse.ProtoReflect.Descriptor instead.
func (*ReplicationIDsResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{12}
}

func (x *ReplicationIDsResponse) GetReplicationId() []string {
	if x != nil {
		return x.ReplicationId
	}
	return nil
}

type ChangeSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          CangeSetRequestType    `protobuf:"varint,2,opt,name=type,proto3,enum=sql.v1.CangeSetRequestType" json:"type,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	ReplicationId string                 `protobuf:"bytes,4,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Strategy      string                 `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Changes       []*Change              `protobuf:"bytes,7,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSetRequest) Reset() {
	*x = ChangeSetRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSetRequest) ProtoMessage() {}

func (x *ChangeSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSetRequest.ProtoReflect.Descriptor instead.
func (*ChangeSetRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeSetRequest) GetType() CangeSetRequestType {
	if x != nil {
		return x.Type
	}
	return CangeSetRequestType_CHANGESET_REQUEST_TYPE_PING
}

func (x *ChangeSetRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ChangeSetRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *ChangeSetRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ChangeSetRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ChangeSetRequest) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

type ChangeSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSetResponse) Reset() {
	*x = ChangeSetResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSetResponse) ProtoMessage() {}

func (x *ChangeSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSetResponse.ProtoReflect.Descriptor instead.
func (*ChangeSetResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeSetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Columns       []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	PkColumns     []string               `protobuf:"bytes,4,rep,name=pk_columns,json=pkColumns,proto3" json:"pk_columns,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	OldRowid      int64                  `protobuf:"varint,6,opt,name=old_rowid,json=oldRowid,proto3" json:"old_rowid,omitempty"`
	NewRowid      int64                  `protobuf:"varint,7,opt,name=new_rowid,json=newRowid,proto3" json:"new_rowid,omitempty"`
	OldValues     []*anypb.Any           `protobuf:"bytes,8,rep,name=old_values,json=oldValues,proto3" json:"old_values,omitempty"`
	NewValues     []*anypb.Any           `protobuf:"bytes,9,rep,name=new_values,json=newValues,proto3" json:"new_values,omitempty"`
	Command       string                 `protobuf:"bytes,10,opt,name=command,proto3" json:"command,omitempty"`
	Args          []*anypb.Any           `protobuf:"bytes,11,rep,name=args,proto3" json:"args,omitempty"`
	TsNs          int64                  `protobuf:"varint,12,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_sql_v1_sql_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{15}
}

func (x *Change) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Change) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Change) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Change) GetPkColumns() []string {
	if x != nil {
		return x.PkColumns
	}
	return nil
}

func (x *Change) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Change) GetOldRowid() int64 {
	if x != nil {
		return x.OldRowid
	}
	return 0
}

func (x *Change) GetNewRowid() int64 {
	if x != nil {
		return x.NewRowid
	}
	return 0
}

func (x *Change) GetOldValues() []*anypb.Any {
	if x != nil {
		return x.OldValues
	}
	return nil
}

func (x *Change) GetNewValues() []*anypb.Any {
	if x != nil {
		return x.NewValues
	}
	return nil
}

func (x *Change) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Change) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Change) GetTsNs() int64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

var File_sql_v1_sql_proto protoreflect.FileDescriptor

const file_sql_v1_sql_proto_rawDesc = "" +
	"\n" +
	"\x10sql/v1/sql.proto\x12\x06sql.v1\x1a\x19google/protobuf/any.proto\"\x9a\x01\n" +
	"\fQueryRequest\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.sql.v1.QueryTypeR\x04type\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12*\n" +
	"\x06params\x18\x03 \x03(\v2\x12.sql.v1.NamedValueR\x06params\x12%\n" +
	"\x0ereplication_id\x18\x04 \x01(\tR\rreplicationId\"f\n" +
	"\n" +
	"NamedValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x03R\aordinal\x12*\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xb3\x01\n" +
	"\rQueryResponse\x12+\n" +
	"\n" +
	"result_set\x18\x01 \x01(\v2\f.sql.v1.DataR\tresultSet\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x03R\frowsAffected\x12$\n" +
	"\x0elast_insert_id\x18\x03 \x01(\x03R\flastInsertId\x12\x14\n" +
	"\x05txseq\x18\x04 \x01(\x04R\x05txseq\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"A\n" +
	"\x04Data\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x1f\n" +
	"\x04rows\x18\x02 \x03(\v2\v.sql.v1.RowR\x04rows\"3\n" +
	"\x03Row\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\x06values\"\x18\n" +
	"\x16DataSourceNamesRequest\"+\n" +
	"\x17DataSourceNamesResponse\x12\x10\n" +
	"\x03dsn\x18\x01 \x03(\tR\x03dsn\"8\n" +
	"\x0fDownloadRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\tR\rreplicationId\"&\n" +
	"\x10DownloadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\">\n" +
	"\x15LatestSnapshotRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\tR\rreplicationId\",\n" +
	"\x16LatestSnapshotResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x17\n" +
	"\x15ReplicationIDsRequest\"?\n" +
	"\x16ReplicationIDsResponse\x12%\n" +
	"\x0ereplication_id\x18\x01 \x03(\tR\rreplicationId\"\xf7\x01\n" +
	"\x10ChangeSetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.sql.v1.CangeSetRequestTypeR\x04type\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12%\n" +
	"\x0ereplication_id\x18\x04 \x01(\tR\rreplicationId\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs\x12\x1a\n" +
	"\bstrategy\x18\x06 \x01(\tR\bstrategy\x12(\n" +
	"\achanges\x18\a \x03(\v2\x0e.sql.v1.ChangeR\achanges\")\n" +
	"\x11ChangeSetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x8e\x03\n" +
	"\x06Change\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12\x1d\n" +
	"\n" +
	"pk_columns\x18\x04 \x03(\tR\tpkColumns\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x1b\n" +
	"\told_rowid\x18\x06 \x01(\x03R\boldRowid\x12\x1b\n" +
	"\tnew_rowid\x18\a \x01(\x03R\bnewRowid\x123\n" +
	"\n" +
	"old_values\x18\b \x03(\v2\x14.google.protobuf.AnyR\toldValues\x123\n" +
	"\n" +
	"new_values\x18\t \x03(\v2\x14.google.protobuf.AnyR\tnewValues\x12\x18\n" +
	"\acommand\x18\n" +
	" \x01(\tR\acommand\x12(\n" +
	"\x04args\x18\v \x03(\v2\x14.google.protobuf.AnyR\x04args\x12\x13\n" +
	"\x05ts_ns\x18\f \x01(\x03R\x04tsNs*s\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16QUERY_TYPE_EXEC_UPDATE\x10\x01\x12\x19\n" +
	"\x15QUERY_TYPE_EXEC_QUERY\x10\x02\x12\x13\n" +
	"\x0fQUERY_TYPE_PING\x10\x03*\xed\x01\n" +
	"\x13CangeSetRequestType\x12\x1f\n" +
	"\x1bCHANGESET_REQUEST_TYPE_PING\x10\x00\x12\"\n" +
	"\x1eCHANGESET_REQUEST_TYPE_PREPARE\x10\x01\x12!\n" +
	"\x1dCHANGESET_REQUEST_TYPE_COMMIT\x10\x02\x12 \n" +
	"\x1cCHANGESET_REQUEST_TYPE_ABORT\x10\x03\x12\x1f\n" +
	"\x1bCHANGESET_REQUEST_TYPE_UNDO\x10\x04\x12+\n" +
	"'CHANGESET_REQUEST_TYPE_UNDO_AFTER_CRASH\x10\x052\xd6\x03\n" +
	"\x0fDatabaseService\x12:\n" +
	"\x05Query\x12\x14.sql.v1.QueryRequest\x1a\x15.sql.v1.QueryResponse\"\x00(\x010\x01\x12T\n" +
	"\x0fDataSourceNames\x12\x1e.sql.v1.DataSourceNamesRequest\x1a\x1f.sql.v1.DataSourceNamesResponse\"\x00\x12A\n" +
	"\bDownload\x12\x17.sql.v1.DownloadRequest\x1a\x18.sql.v1.DownloadResponse\"\x000\x01\x12S\n" +
	"\x0eLatestSnapshot\x12\x1d.sql.v1.LatestSnapshotRequest\x1a\x1e.sql.v1.LatestSnapshotResponse\"\x000\x01\x12Q\n" +
	"\x0eReplicationIDs\x12\x1d.sql.v1.ReplicationIDsRequest\x1a\x1e.sql.v1.ReplicationIDsResponse\"\x00\x12F\n" +
	"\tChangeSet\x12\x18.sql.v1.ChangeSetRequest\x1a\x19.sql.v1.ChangeSetResponse\"\x00(\x010\x01B+Z)github.com/litesql/go-ha/api/sql/v1;sqlv1b\x06proto3"

var (
	file_sql_v1_sql_proto_rawDescOnce sync.Once
	file_sql_v1_sql_proto_rawDescData []byte
)

func file_sql_v1_sql_proto_rawDescGZIP() []byte {
	file_sql_v1_sql_proto_rawDescOnce.Do(func() {
		file_sql_v1_sql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sql_v1_sql_proto_rawDesc), len(file_sql_v1_sql_proto_rawDesc)))
	})
	return file_sql_v1_sql_proto_rawDescData
}

var file_sql_v1_sql_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sql_v1_sql_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_sql_v1_sql_proto_goTypes = []any{
	(QueryType)(0),                  // 0: sql.v1.QueryType
	(CangeSetRequestType)(0),        // 1: sql.v1.CangeSetRequestType
	(*QueryRequest)(nil),            // 2: sql.v1.QueryRequest
	(*NamedValue)(nil),              // 3: sql.v1.NamedValue
	(*QueryResponse)(nil),           // 4: sql.v1.QueryResponse
	(*Data)(nil),                    // 5: sql.v1.Data
	(*Row)(nil),                     // 6: sql.v1.Row
	(*DataSourceNamesRequest)(nil),  // 7: sql.v1.DataSourceNamesRequest
	(*DataSourceNamesResponse)(nil), // 8: sql.v1.DataSourceNamesResponse
	(*DownloadRequest)(nil),         // 9: sql.v1.DownloadRequest
	(*DownloadResponse)(nil),        // 10: sql.v1.DownloadResponse
	(*LatestSnapshotRequest)(nil),   // 11: sql.v1.LatestSnapshotRequest
	(*LatestSnapshotResponse)(nil),  // 12: sql.v1.LatestSnapshotResponse
	(*ReplicationIDsRequest)(nil),   // 13: sql.v1.ReplicationIDsRequest
	(*ReplicationIDsResponse)(nil),  // 14: sql.v1.ReplicationIDsResponse
	(*ChangeSetRequest)(nil),        // 15: sql.v1.ChangeSetRequest
	(*ChangeSetResponse)(nil),       // 16: sql.v1.ChangeSetResponse
	(*Change)(nil),                  // 17: sql.v1.Change
	(*anypb.Any)(nil),               // 18: google.protobuf.Any
}
var file_sql_v1_sql_proto_depIdxs = []int32{
	0,  // 0: sql.v1.QueryRequest.type:type_name -> sql.v1.QueryType
	3,  // 1: sql.v1.QueryRequest.params:type_name -> sql.v1.NamedValue
	18, // 2: sql.v1.NamedValue.value:type_name -> google.protobuf.Any
	5,  // 3: sql.v1.QueryResponse.result_set:type_name -> sql.v1.Data
	6,  // 4: sql.v1.Data.rows:type_name -> sql.v1.Row
	18, // 5: sql.v1.Row.values:type_name -> google.protobuf.Any
	1,  // 6: sql.v1.ChangeSetRequest.type:type_name -> sql.v1.CangeSetRequestType
	17, // 7: sql.v1.ChangeSetRequest.changes:type_name -> sql.v1.Change
	18, // 8: sql.v1.Change.old_values:type_name -> google.protobuf.Any
	18, // 9: sql.v1.Change.new_values:type_name -> google.protobuf.Any
	18, // 10: sql.v1.Change.args:type_name -> google.protobuf.Any
	2,  // 11: sql.v1.DatabaseService.Query:input_type -> sql.v1.QueryRequest
	7,  // 12: sql.v1.DatabaseService.DataSourceNames:input_type -> sql.v1.DataSourceNamesRequest
	9,  // 13: sql.v1.DatabaseService.Download:input_type -> sql.v1.DownloadRequest
	11, // 14: sql.v1.DatabaseService.LatestSnapshot:input_type -> sql.v1.LatestSnapshotRequest
	13, // 15: sql.v1.DatabaseService.ReplicationIDs:input_type -> sql.v1.ReplicationIDsRequest
	15, // 16: sql.v1.DatabaseService.ChangeSet:input_type -> sql.v1.ChangeSetRequest
	4,  // 17: sql.v1.DatabaseService.Query:output_type -> sql.v1.QueryResponse
	8,  // 18: sql.v1.DatabaseService.DataSourceNames:output_type -> sql.v1.DataSourceNamesResponse
	10, // 19: sql.v1.DatabaseService.Download:output_type -> sql.v1.DownloadResponse
	12, // 20: sql.v1.DatabaseService.LatestSnapshot:output_type -> sql.v1.LatestSnapshotResponse
	14, // 21: sql.v1.DatabaseService.ReplicationIDs:output_type -> sql.v1.ReplicationIDsResponse
	16, // 22: sql.v1.DatabaseService.ChangeSet:output_type -> sql.v1.ChangeSetResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sql_v1_sql_proto_init() }
func file_sql_v1_sql_proto_init() {
	if File_sql_v1_sql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sql_v1_sql_proto_rawDesc), len(file_sql_v1_sql_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sql_v1_sql_proto_goTypes,
		DependencyIndexes: file_sql_v1_sql_proto_depIdxs,
		EnumInfos:         file_sql_v1_sql_proto_enumTypes,
		MessageInfos:      file_sql_v1_sql_proto_msgTypes,
	}.Build()
	File_sql_v1_sql_proto = out.File
	file_sql_v1_sql_proto_goTypes = nil
	file_sql_v1_sql_proto_depIdxs = nil
}
