// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sql/v1/sql.proto

package sqlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED QueryType = 0
	QueryType_QUERY_TYPE_EXEC        QueryType = 1
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_EXEC",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED": 0,
		"QUERY_TYPE_EXEC":        1,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_sql_v1_sql_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_sql_v1_sql_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          QueryType              `protobuf:"varint,1,opt,name=type,proto3,enum=sql.v1.QueryType" json:"type,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Params        []*NamedValue          `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	ReplicationId string                 `protobuf:"bytes,4,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sql_v1_sql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetType() QueryType {
	if x != nil {
		return x.Type
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParams() []*NamedValue {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

type NamedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ordinal       int64                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedValue) Reset() {
	*x = NamedValue{}
	mi := &file_sql_v1_sql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedValue) ProtoMessage() {}

func (x *NamedValue) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedValue.ProtoReflect.Descriptor instead.
func (*NamedValue) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{1}
}

func (x *NamedValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedValue) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *NamedValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultSet     *Data                  `protobuf:"bytes,1,opt,name=result_set,json=resultSet,proto3" json:"result_set,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	LastInsertId  int64                  `protobuf:"varint,3,opt,name=last_insert_id,json=lastInsertId,proto3" json:"last_insert_id,omitempty"`
	Txseq         uint64                 `protobuf:"varint,4,opt,name=txseq,proto3" json:"txseq,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sql_v1_sql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetResultSet() *Data {
	if x != nil {
		return x.ResultSet
	}
	return nil
}

func (x *QueryResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryResponse) GetLastInsertId() int64 {
	if x != nil {
		return x.LastInsertId
	}
	return 0
}

func (x *QueryResponse) GetTxseq() uint64 {
	if x != nil {
		return x.Txseq
	}
	return 0
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_sql_v1_sql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Data) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*anypb.Any           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_sql_v1_sql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_sql_v1_sql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_sql_v1_sql_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetValues() []*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_sql_v1_sql_proto protoreflect.FileDescriptor

const file_sql_v1_sql_proto_rawDesc = "" +
	"\n" +
	"\x10sql/v1/sql.proto\x12\x06sql.v1\x1a\x19google/protobuf/any.proto\"\x9a\x01\n" +
	"\fQueryRequest\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.sql.v1.QueryTypeR\x04type\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12*\n" +
	"\x06params\x18\x03 \x03(\v2\x12.sql.v1.NamedValueR\x06params\x12%\n" +
	"\x0ereplication_id\x18\x04 \x01(\tR\rreplicationId\"f\n" +
	"\n" +
	"NamedValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x03R\aordinal\x12*\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xb3\x01\n" +
	"\rQueryResponse\x12+\n" +
	"\n" +
	"result_set\x18\x01 \x01(\v2\f.sql.v1.DataR\tresultSet\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x03R\frowsAffected\x12$\n" +
	"\x0elast_insert_id\x18\x03 \x01(\x03R\flastInsertId\x12\x14\n" +
	"\x05txseq\x18\x04 \x01(\x04R\x05txseq\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"A\n" +
	"\x04Data\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x1f\n" +
	"\x04rows\x18\x02 \x03(\v2\v.sql.v1.RowR\x04rows\"3\n" +
	"\x03Row\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\x06values*<\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUERY_TYPE_EXEC\x10\x012M\n" +
	"\x0fDatabaseService\x12:\n" +
	"\x05Query\x12\x14.sql.v1.QueryRequest\x1a\x15.sql.v1.QueryResponse\"\x00(\x010\x01B+Z)github.com/litesql/go-ha/api/sql/v1;sqlv1b\x06proto3"

var (
	file_sql_v1_sql_proto_rawDescOnce sync.Once
	file_sql_v1_sql_proto_rawDescData []byte
)

func file_sql_v1_sql_proto_rawDescGZIP() []byte {
	file_sql_v1_sql_proto_rawDescOnce.Do(func() {
		file_sql_v1_sql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sql_v1_sql_proto_rawDesc), len(file_sql_v1_sql_proto_rawDesc)))
	})
	return file_sql_v1_sql_proto_rawDescData
}

var file_sql_v1_sql_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sql_v1_sql_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sql_v1_sql_proto_goTypes = []any{
	(QueryType)(0),        // 0: sql.v1.QueryType
	(*QueryRequest)(nil),  // 1: sql.v1.QueryRequest
	(*NamedValue)(nil),    // 2: sql.v1.NamedValue
	(*QueryResponse)(nil), // 3: sql.v1.QueryResponse
	(*Data)(nil),          // 4: sql.v1.Data
	(*Row)(nil),           // 5: sql.v1.Row
	(*anypb.Any)(nil),     // 6: google.protobuf.Any
}
var file_sql_v1_sql_proto_depIdxs = []int32{
	0, // 0: sql.v1.QueryRequest.type:type_name -> sql.v1.QueryType
	2, // 1: sql.v1.QueryRequest.params:type_name -> sql.v1.NamedValue
	6, // 2: sql.v1.NamedValue.value:type_name -> google.protobuf.Any
	4, // 3: sql.v1.QueryResponse.result_set:type_name -> sql.v1.Data
	5, // 4: sql.v1.Data.rows:type_name -> sql.v1.Row
	6, // 5: sql.v1.Row.values:type_name -> google.protobuf.Any
	1, // 6: sql.v1.DatabaseService.Query:input_type -> sql.v1.QueryRequest
	3, // 7: sql.v1.DatabaseService.Query:output_type -> sql.v1.QueryResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sql_v1_sql_proto_init() }
func file_sql_v1_sql_proto_init() {
	if File_sql_v1_sql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sql_v1_sql_proto_rawDesc), len(file_sql_v1_sql_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sql_v1_sql_proto_goTypes,
		DependencyIndexes: file_sql_v1_sql_proto_depIdxs,
		EnumInfos:         file_sql_v1_sql_proto_enumTypes,
		MessageInfos:      file_sql_v1_sql_proto_msgTypes,
	}.Build()
	File_sql_v1_sql_proto = out.File
	file_sql_v1_sql_proto_goTypes = nil
	file_sql_v1_sql_proto_depIdxs = nil
}
